### ISSUE TITLE
v15.6.1 does not resolve

### ISSUE THREAD

**Issue by dazraf** [webjars/react#31]
```
    <dependency>
      <groupId>org.webjars.npm</groupId>
      <artifactId>react</artifactId>
      <version>15.6.1</version>
    </dependency>
```

Results in:
```
Could not resolve dependencies for project io.dazraf.reactx:example-web:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.webjars.npm:react:jar:15
.6.1 -> org.webjars.npm:fbjs:jar:0.9.0-alpha.2 -> org.webjars.npm:fbjs-css-vars:jar:[1.0.0,2): No versions available for org.webjars.npm:fbjs-css-vars:jar:[1.0.0,2) within specified range
```

**Comment by dazraf** [comment]
Also same result for all versions of react. Dependency to fbjs:0.9.0-alpha.2 never fully resolves because of missing fbjs-css-vars dependency.

**Comment by jamesward** [comment]
This repo is for the Classic React WebJar.  In the future for NPM WebJars please file issues at https://github.com/webjars/webjars/issues

Have you tried to deploy the missing dependencies using the form on http://webjars.org ?

**Comment by dazraf** [comment]
Thanks James. In future will raise on repo you stated. "deploy the missing ... using the form .." Which form please? The search form? When I type "fbjs-css-vars" the dependency doesn't exist and there are no options to deploy it. Sorry for the dumb question :-)

**Comment by jamesward** [comment]
No worries.  Click the "Add a WebJar" button.

**Comment by dazraf** [comment]
Ah thanks! I don't know why I didn't see that. Presumably all modules are deployed that way. Perhaps I can submit a PR to automatically deploy missing dependencies as well.

**Comment by jamesward** [comment]
NPM & Bower WebJars can be deployed that way.  Classic ones are deployed manually.  We've talked about automating releases but don't want to pollute Maven Central with TBs of unnecessary modules.
