### ISSUE TITLE
Please Release Version: 16.4.2

### ISSUE THREAD

**Issue by kevinmwangi** [webjars/react#34]

**Comment by kevinmwangi** [comment]
Hi @jamesward Thanks for resolving this, However could you add react-dom, I would appreciate, Again thanks.

**Comment by jamesward** [comment]
I'm not sure what you need.  Something on this WebJar or a different one?

**Comment by kevinmwangi** [comment]
I need react-dom.production.min.js and  react-dom.development.js files added
